# Generated by Django 4.2.7 on 2023-11-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='kitchen_service.dish'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(choices=[('tea spoon', 'tea spoon'), ('milligrams', 'milligrams'), ('milliliter', 'milliliter'), ('kitchen spoon', 'kitchen spoon'), ('liter', 'liter'), ('grams', 'grams'), ('unit', 'unit'), ('kilograms', 'kilograms')], default='unit', max_length=255),
        ),
    ]
